"use client"

import { Inter } from 'next/font/google'
import NavBar from './components/NavBar'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap'
import Footer from './components/Footer';
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Practice Next App',
  description: 'Generated by Md.Manirul Islam',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
        <div className="container">
          <NavBar />
          {children}
          <ProgressBar height='3px' color="#fffd00" options={{ showSpinner: false }} shallowRouting/>
          <Footer />
        </div>
      </body>
    </html>
  )
}
